feat(upshot): Build Upshot Adapter
linkpoolio/external-adapters-js pull request #108
Opened 2022-03-11 13:07 UTC by 1marcghannam

2022-03-11 13:44 UTC, jnapprogs requested changes
Had a quick question, but looks good 👍

2022-03-11 13:44 UTC, jnapprogs commented on packages/sources/upshot/src/endpoint/floor-price.ts
> +export const endpointResultPaths = {}
Is it safe to remove this variable?

2022-03-14 14:59 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/floor-price.ts
> +export const endpointResultPaths = {}
Good question. It is safe to delete it but also Chainlink leaves it empty, so let's keep it empty.

2022-03-14 15:16 UTC, vnavascues approved these changes
LGTM!

2022-03-14 15:29 UTC, merged