feat(upshot): Update assetAddress param
linkpoolio/external-adapters-js pull request #133
Opened 2022-05-06 14:58 UTC by 1marcghannam

2022-05-09 19:55 UTC, ericjaurena requested changes
in README.md lines 27 and 85 should be changed to reflect that the prices returned by the Upshot adapter are measured in `WEI` and not `GWEI`

2022-05-13 15:04 UTC, vnavascues approved these changes
Excellent! approved it. Just take care of the minor changes before merging it :)

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/package.json
>    "dependencies": {
You must bump the version to `1.1.0` after adding a new endpoint

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/statistics.ts
> +export const description =
This is outdated. Fix it and regenerate the docs

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/asset-price.ts
> +  'This endpoint allows you to query the price in WEI for a specific NFT asset.'
`This endpoint allows you to query the floor price in wei for a specific NFT asset.`

`wei` is not in capital case, `wei` or `Wei` (after a period). ETH although is accepted!

By making the price returned is the "floor" then you can simplify `assetAddress` and `tokenId` descriptions:
- `The NFT collection address`
- `The NFT ID`

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/asset-price.ts
> +    const message = (error as Error).message
This is not needed, check the `Error` documentation.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message

`${error}` will call `toString()` which already includes `message`.

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/asset-price.ts
> +      message: `Unexpected error occurred parsing the estimated price from the API response. ${message}`,
`blabla message. ${error}`

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/statistics.ts
> +    const message = (error as Error).message
This is not needed, check the `Error` documentation.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message

`${error}` will call t`oString()` which already includes `message`.

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/statistics.ts
> +  response.data.result = result
Maaaaaaarc, result is a String, you should return `withResult`

https://github.com/linkpoolio/external-adapters-js/pull/132#discussion_r863663006

2022-05-13 15:04 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/statistics.ts
> +  const url = `/v1/collections/contractaddress/${assetAddress}`
you should use `buildUrlPath`

2022-05-13 15:28 UTC, vnavascues commented on packages/sources/upshot/src/endpoint/statistics.ts
> +  response.data.result = result
Apologies, it is indeed an object. You did right!

2022-05-13 16:46 UTC, merged