feat(artcentral): Build adapter
linkpoolio/external-adapters-js pull request #149
Opened 2022-06-08 13:46 UTC by 1marcghannam

2022-06-10 16:21 UTC, vnavascues requested changes
Please, pay attention to big numbers and addresses format, we've talked about them many times. Always have in mind the `MAX_SAFE_INTEGER`. Always test the API with different address formats, e.g. lowercase, checksum, mixed case.

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/test/integration/tami.ts
> +import { assertError, assertSuccess } from '@chainlink/ea-test-helpers'
Please, always run `yarn lint`:
![image](https://user-images.githubusercontent.com/14769962/173090512-f41d1f9a-a636-4318-88f3-0d27d1d12a5e.png)

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/schemas/env.json
> +      "description": "API key taht can be obtained from [ArtCentral](https://artcentral.io/)",
`that`

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/src/endpoint/tami.ts
> +  const isError = data.TAMI == undefined
Idk whether done in purpose or not, but with `==` also covers the `null` case, which is OK

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/src/endpoint/tami.ts
> +      message: `There was an unexpected error parsing the result.`,
Clearly include the `response.data.TAMI` in the message.

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/src/lib/const.ts
> +export const WEI_MULTIPLIER = 1000000000000000000
VS Code should warn you about:
```
Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers.ts(80008)
```

More on `tami.ts` comments

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/src/endpoint/tami.ts
> +  const result = response.data.TAMI * WEI_MULTIPLIER
BUG: Please, remember than in JavaScript the `MAX_SAFE_INTEGER` is `9007199254740991` (`2^53 - 1`)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

`WEI_MULTIPLIER > MAX_SAFE_INTEGER`, which means `const result = response.data.TAMI * WEI_MULTIPLIER` is not safe.

Install ethers.js and use `BigNumber` to format `response.data.TAMI` in `wei` (you won't need the `WEI_MULTIPLIER`).
https://docs.ethers.io/v5/api/utils/display-logic/#utils-parseUnits

Then return it as result either as `number` or `string`. I think there is no problem encoding a JSON `string` to `uint256` at TOML level (unless Golang can't handle exponents, e.g. `e+23`)

2022-06-10 16:21 UTC, vnavascues commented on packages/sources/artcentral/src/endpoint/tami.ts
> +  const url = util.buildUrlPath(`/collectibles/:assetAddress/appraisal`, { assetAddress })
BUG: `assetAddress` requires to be lower cased. The API is case sensitive and does not accept any other format than lower case addresses (at least tested for Azuki). Sending the addresses as bytes and then decoding them via `base64-decoder` will always return a lower case address, but the adapter alone should make sure addresses are lower cased.

2022-06-13 20:00 UTC, 1marcghannam commented on packages/sources/artcentral/src/endpoint/tami.ts
> +  const result = response.data.TAMI * WEI_MULTIPLIER
I used ethers to format to wei and returned it as a number. I tried returning as string, encoding in the job spec, `"152107753147022770000000"` encoded returned `0x9a91eb0d000000000000000000000000000000000000000000002035c71f41cd39a55080`. My task looked like this `encode [type="ethabiencode"
        abi="fulfillRequest(uint256 result)"
        data="{\\"result\\": $(result_parse)}"
        ]`
       The correct encoding to uint256 would be the same without `9a91eb0d` at the start.

2022-06-15 13:21 UTC, merged