feat(blocknative): added legacy and EIP-1559 gas price endpoints
linkpoolio/external-adapters-js pull request #55
Opened 2021-09-13 18:17 UTC by vnavascues

Pending:
- Test it with premium credentials.

Endpoints:
- `blockprices-legacy`: requires `confidenceLevel` param (integer from 1 to 99, both included). Returns an integer (wei) to be consumed as `uint`.
- `blockprices-eip1559`: requires `confidenceLevel` param (integer from 1 to 99, both included). Returns a string to be consumer as `bytes32`.

2021-09-15 15:23 UTC, 1marcghannam commented on packages/sources/blocknative/test/unit/blockprices-eip1559.test.ts
> +              season: 'LinkPool'
Season needs to be confidenceLevel instead.

2021-09-15 15:29 UTC, 1marcghannam requested changes
Very small typo in tests. season param should be confidenceLevel

2021-09-15 15:29 UTC, 1marcghannam commented on packages/sources/blocknative/test/unit/blockprices-eip1559.test.ts
> +              season: 'LinkPool'
Season needs to be confidenceLevel.

2021-09-15 15:29 UTC, 1marcghannam commented on packages/sources/blocknative/test/unit/blockprices-legacy.test.ts
> +              season: 'LinkPool'
Season needs to be confidenceLevel.

2021-09-15 18:10 UTC, vnavascues commented on packages/sources/blocknative/test/unit/blockprices-eip1559.test.ts
> +              season: 'LinkPool'
Spotted on! Thanks Marc

2021-09-15 18:10 UTC, vnavascues commented on packages/sources/blocknative/test/unit/blockprices-legacy.test.ts
> +              season: 'LinkPool'
Spotted on! Thanks Marc

2021-09-16 15:45 UTC, 1marcghannam approved these changes

2021-09-16 15:47 UTC, merged