feat(heni): create HENI adapter
linkpoolio/external-adapters-js pull request #75
Opened 2022-01-12 19:09 UTC by 1marcghannam

2022-01-12 20:55 UTC, christianagnew requested changes

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/test/integration/price.test.ts
> +          chainId: 'linkpool',
Should this be 'collectionId'?

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/test/integration/price.test.ts
> +            collection: 1,
Same as comment below

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/test-payload.json
> +{
Is this file used for anything?

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/src/endpoint/price.ts
> +export const collectionIdToCollection: Map<number, string> = new Map([[1, 'thecurrency']])
Is there any reason for mapping collectionIds to collection names instead of just taking the collection name as an input?

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/test/integration/price.test.ts
> +        assertError({ expected: 400, actual: errorResp.statusCode }, errorResp, jobID)
This assert will only be reached if the adapter throws an error so if it doesn't throw an error the test will pass when it should fail

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/test/integration/price.test.ts
> +        assertError({ expected: 400, actual: errorResp.statusCode }, errorResp, jobID)
This assert will only be reached if the adapter throws an error so if it doesn't throw an error the test will pass when it should fail

2022-01-12 20:55 UTC, christianagnew commented on packages/sources/heni/test/integration/price.test.ts
> +            collection: 1,
Same as below

2022-01-12 20:59 UTC, 1marcghannam commented on packages/sources/heni/test/integration/price.test.ts
> +          chainId: 'linkpool',
Yes I will change that, copy pasta mistake :)

2022-01-12 20:59 UTC, 1marcghannam commented on packages/sources/heni/test/integration/price.test.ts
> +            collection: 1,
Will do!

2022-01-12 21:00 UTC, 1marcghannam commented on packages/sources/heni/test-payload.json
> +{
Will remove this file since its useless

2022-01-12 21:01 UTC, 1marcghannam commented on packages/sources/heni/src/endpoint/price.ts
> +export const collectionIdToCollection: Map<number, string> = new Map([[1, 'thecurrency']])
Created a map so later on if they decide to add more collections to the list, we can just add them to the map.

2022-01-12 21:01 UTC, 1marcghannam commented on packages/sources/heni/test/integration/price.test.ts
> +            collection: 1,
Will change

2022-01-12 21:11 UTC, 1marcghannam commented on packages/sources/heni/test/integration/price.test.ts
> +        assertError({ expected: 400, actual: errorResp.statusCode }, errorResp, jobID)
I will completely remove this test since it's not useful, I am already testing the validation for collectionId in unit test.

2022-01-12 22:05 UTC, jnapprogs commented on packages/sources/heni/CHANGELOG.md
> +# @chainlink/example-source-adapter
Just to confirm: this file is generated automatically?

2022-01-12 22:09 UTC, jnapprogs commented on packages/sources/heni/test/integration/price.test.ts
> +        },
For this test, are we confirming that we are able to call the endpoint successfully without worrying about actual results?

2022-01-12 22:10 UTC, jnapprogs reviewed
Just have a couple of questions.  Aside from that, it looks good!  🚀

2022-01-12 22:13 UTC, 1marcghannam commented on packages/sources/heni/CHANGELOG.md
> +# @chainlink/example-source-adapter
Yes

2022-01-12 22:17 UTC, 1marcghannam commented on packages/sources/heni/test/integration/price.test.ts
> +        },
I am just making sure the api call goes through when inputs are valid and that the result type is a number in this case.

2022-01-12 22:29 UTC, merged

2022-01-13 17:48 UTC, jnapprogs commented on packages/sources/heni/CHANGELOG.md
> +# @chainlink/example-source-adapter
👍

2022-01-13 17:48 UTC, jnapprogs commented on packages/sources/heni/test/integration/price.test.ts
> +        },
👍