NFTBank integration tests
linkpoolio/external-adapters-js pull request #96
Opened 2022-03-01 08:00 UTC by jnapprogs

## Closes sc-3129

## Description
Integration test for NFTBank

2022-03-01 12:18 UTC, vnavascues requested changes
Juan I was expecting to see the revamp (bugfixes + refactor) included in this PR, for instance:
- Better extensibility: `NFTCollection` as Map, don't use `getNftCollection()`, improved `getEstimateFor()`.
- Don't overwrite the real API result: don't use `createResultData()`.
- Support `0` price: don't use `Requester.validateResultNumber()` (throws an error), don't use `createResultData()` (sets `item_found` to false if `estimate` is falsy).
- Don't use `Requester.validateResultNumber()` just
- Improved errors: the error in  `getEstimateFor()` should be a simple `throw new Error("<message>")`. Then outside re-raise it as `AdapterError` with a 200 statusCode and including `cause` and `url` properties.
- Delete unused types, variables, etc.

I've added an extra commit with the expected changes. It's linted, it builds however I've not tested it!

2022-03-01 12:18 UTC, vnavascues commented on packages/sources/heni/test/integration/fixtures.ts
> +    .post(`/price`)
Why this change? The `price` endpoint makes a `get` request and nock is incapable of intercepting the request:

```shell
{"level":"error","time":1646132310974,"pid":184977,"hostname":"victor-Vostro-7590","message":"AdapterError: Request failed with status code 500","jobRunID":"1","params":{"endpoint":"nftbank","nftCollection":0,"nftId":1,"pricingAsset":"ETH","resultPath":"nftbank"},"feedID":"{\"data\":{\"endpoint\":\"nftbank\",\"nftCollection\":0,\"nftId\":1,\"pricingAsset\":\"ETH\",\"resultPath\":\"nftbank\"}}","url":"https:/api.nftbank.ai/estimates-v2/estimates/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/1"}
```

2022-03-01 12:18 UTC, vnavascues commented on packages/sources/nftbank/package.json
> +    "nock": "^13.2.4",
please remove the caret `^`, we do follow Chainlink practices and they remove them on `devDependiencies`

2022-03-02 05:12 UTC, jnapprogs commented on packages/sources/heni/test/integration/fixtures.ts
> +    .post(`/price`)
Oh snap.  I did not mean to make this change.  I shall go and revert it.

2022-03-02 06:23 UTC, jnapprogs commented
@vnavascues, I have renamed the branch to better align with the ticket.  I will go ahead and close this PR and reference the new PR in this comment

2022-03-02 06:23 UTC, closed without merging