Feature/sc 3367/tac index
linkpoolio/external-adapters-js pull request #99
Opened 2022-03-02 23:42 UTC by 1marcghannam

2022-03-02 23:47 UTC, 1marcghannam reviewed
-Not sure how to implement ResponseSchema type with the response as array, having some trouble

2022-03-03 13:04 UTC, vnavascues requested changes
I believe the authorization method of this API is Basic auth, instead of API key.
Nothing stops you of using `API_KEY` with the base64 encoded `username` and `password`, but you should leverage the axios `RequestConfig.auth`, which deals with it for you. Instead of `API_KEY` you should use `API_USERNAME` & `API_PASSWORD` (both required). Also it is more maintainable and understandable for everyone (business devs, infra team & integrations team).

From axios [RequestConfig](https://github.com/axios/axios#response-schema):
```typescript
  // `auth` indicates that HTTP Basic auth should be used, and supplies credentials.
  // This will set an `Authorization` header, overwriting any existing
  // `Authorization` custom headers you have set using `headers`.
  // Please note that only HTTP Basic auth is configurable through this parameter.
  // For Bearer tokens and such, use `Authorization` custom headers instead.
  auth: {
    username: 'janedoe',
    password: 's00pers3cret'
  },
  ```

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/config/index.ts
> +  const config = Requester.getDefaultConfig(prefix)
1. By passing `true` as a second parameter to `getDefaultConfig()` you are making `API_KEY` required. Then you can remove the next line (as the `API_KEY` value will be stored in `config.apiKey`).
https://github.com/smartcontractkit/external-adapters-js/blob/develop/packages/core/bootstrap/src/lib/config/index.ts#L27

2. This file is more or less about the EA configuration (`Config`), including too the API config. I'd rather having in this file any invariable/immutable config across the EA endpoints than in the particular endpoint file(s). And in fact this is why `baseURL` is here. Please, move the headers initialisation from `price.ts` to here:
```typescript
config.api.headers['Authorization'] = config.apiKey
```

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/lib/utils.ts
> +import { Currency } from './const'
There are linting warnings:
```shell
/home/pepe/linkpool/external-adapters-js/packages/sources/tac-index/src/lib/utils.ts
  5:46  warning  Missing return type on function                      @typescript-eslint/explicit-module-boundary-types
  5:47  warning  Argument 'data' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
```

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +export const endpointResultPaths = {
This is still in the `example.ts` state. Replace it with:
```typescript
export const endpointResultPaths = {}
```

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +const customError = (data: Record<string, unknown>) => data.Response === 'Error'
nitpick: this is the default behavior. You can remove this `customError` (and remove it from `await Requester.request<ResponseSchema>(options, customError)`)

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +    method: 'get',
nitpick: this is the default method of [axios RequestConfig](https://github.com/axios/axios#request-config), no need to explicitly have it.

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +  response.data.result = price
important: as I've said many times if the API response (`response.data`) is an Array (`[...]`), and not an object (`{...}`), you must not do `response.data.result = price` and allowing `config.verbose`. A JSON Array (the EA response) can't have properties (e.g. `result`) and by running this EA with `API_VERBOSE=true` it will misbehave.

When it comes to return just a `number` or `string` result, please use [Requester.withResult()](https://github.com/smartcontractkit/external-adapters-js/blob/develop/packages/core/bootstrap/src/lib/modules/requester.ts#L134), which nicely handles the Array API Response.

Also I reckon this is the reason why your integration test was failing, your `response.data` does not / can't contain `result`. Therefore [assertSuccess()](https://github.com/smartcontractkit/external-adapters-js/blob/develop/packages/core/test-helpers/src/helpers.ts#L20) is failing.

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +  const response = await Requester.request(options, customError)
I'm aware you know this is missing the `<ResponseSchema>`

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +  const routes = response.data
1. Check first `response.data` is an Array.
2. Just declare `price` (do not initialize it to `null`) `let price: number`.
3. Use a `for` loop instead of a `foreEach()`. A `for` loop can be broken with `break`. Please, once you find the `route_code` break the iteration (so you stop going through all the items).
4. The `try...catch` should wrap the `filterPrice()` call, not the whole `if` block.
5. If `price === undefined` then throw the exception you already have (same code).

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/lib/utils.ts
> +/* eslint-disable-next-line @typescript-eslint/no-explicit-any */
`formatNumericEnumValuesPretty` and `validateCurrency` can be removed, they are not needed anymore

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +  try {
This whole block can be removed as `inputParameters.currenty.options` is already doing the same. Also remove them from the `utils.ts` file.

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/lib/utils.ts
> +      `Route: ${routeData} does not have the price for the provided currency: ${currency}`,
Due to `routData` is a JSON object and you are using template literals, you must do `${JSON.stringify(routeData)}`, or you'll just see `[object Object]` being logged.

```
curl --header "Content-Type: application/json" --request POST --data '{"id":"1","data": {"currency": "pepe", "route": "IN-RB1"}}' 'http://localhost:8080'

{"jobRunID":"1","status":"errored","statusCode":200,"error":{"name":"AdapterError","message":"Route: IN-RB1, in currency: PEPE could not be found. Reason: Error: Route: [object Object] does not have the price for the provided currency: PEPE","url":"https:/api.tacindex.com/freight/price/?format=json","feedID":"{\"data\":{\"currency\":\"pepe\",\"route\":\"IN-RB1\",\"endpoint\":\"price\"}}"}}
```

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/lib/utils.ts
> +    return Number(routeData.euro) as number
`Number(routeData.euro)` should be enough, cause Number returns type `number`. This applies to all the cases.

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/config/index.ts
> +  const config = Requester.getDefaultConfig(prefix)
important: isn't the API using Basic Auth? Are you providing as `API_KEY` the `username` & `password` already base64 encoded?

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +  currency: {
important: according to the requirements shouldn't this default to USD? `default: Currency.USD`

2022-03-03 13:04 UTC, vnavascues commented on packages/sources/tac-index/src/endpoint/price.ts
> +    url: `/freight/price/?format=${format}`,
Hard code the `json`.

By default this framework is [`application/json` request & response-oriented](https://github.com/smartcontractkit/external-adapters-js/blob/develop/packages/core/bootstrap/src/lib/config/index.ts#L48). If you attempt to request with `csv` format it won't be accepted by the API and it will return a `406`.

2022-03-03 14:05 UTC, 1marcghannam commented on packages/sources/tac-index/src/endpoint/price.ts
> +    url: `/freight/price/?format=${format}`,
Done

2022-03-03 14:19 UTC, 1marcghannam commented on packages/sources/tac-index/src/config/index.ts
> +  const config = Requester.getDefaultConfig(prefix)
Done

2022-03-03 14:19 UTC, 1marcghannam commented on packages/sources/tac-index/src/lib/utils.ts
> +import { Currency } from './const'
Done

2022-03-03 14:19 UTC, 1marcghannam commented on packages/sources/tac-index/src/endpoint/price.ts
> +export const endpointResultPaths = {
Done

2022-03-03 14:19 UTC, 1marcghannam commented on packages/sources/tac-index/src/endpoint/price.ts
> +const customError = (data: Record<string, unknown>) => data.Response === 'Error'
Done

2022-03-03 14:20 UTC, 1marcghannam commented on packages/sources/tac-index/src/endpoint/price.ts
> +    method: 'get',
Done

2022-03-03 14:22 UTC, 1marcghannam commented on packages/sources/tac-index/src/endpoint/price.ts
> +  response.data.result = price
That was exactly why it failed, so i just turned API_VERBOSE= FALSE in the test :0

2022-03-03 19:46 UTC, 1marcghannam reviewed
Done

2022-03-03 19:47 UTC, merged